/*
OPERADORES ARITMETICOS
 + (SOMA)
 - ( SUBTRACAO )
 * ( MULTIPLICACAO )
 / ( DIVIDIR )
 % ( MODULO ) = RESTO DA DIVISAO
*/

SELECT 1+1 AS ADICAO
SELECT 5 - 10 AS [SUBTRACAO(-1)]

SELECT 2 + 7 * 10 AS MULTIPLICACAO
SELECT 90 / 3 AS DIVISAO
SELECT 90 % 60 AS [RESTO DA DIVISAO] 

SELECT 1 +3 AS SOMA,
       3 - 7 AS SUB,
       1700 +( -900 ) AS NEG,
       5 * (5 +1) AS [MULTIPLACAO SOMA],
       -5 * (500/40) %3 AS TODO
