/*
O GROUP BY BASICAMENTE DIVIDE O RESULTADO DA SUA PESQUISA EM GRUPOS:
- PARA CADA GRUPO VOCE PODE APLICAR UMA FUNÇÃO DE AGREGAÇÃO, POR EXEMPLO:
    - CALCULAR A SOMA DOS ITENS
    - CONTAR O NUMERO DE ITENS NAQUELE GRUPO
*/


SELECT * 
    FROM Sales.SalesOrderDetail

SELECT SpecialOfferID, SUM(UnitPrice)
    FROM Sales.SalesOrderDetail
    GROUP BY SpecialOfferID


--QUANTOS DE CADA PRODUTO FOI VENDIDO ATÉ HOJE

SELECT ProductID, COUNT(ProductID) AS 'SOMA'
    FROM Sales.SalesOrderDetail
    GROUP BY ProductID

-- QUANTOS NOMES DE CADA NOME TEMOS CADASTRADOS EM NOSSO BANCO DE DADOS

SELECT FirstName, COUNT (FirstName) AS 'CONTAGEM'
    FROM Person.Person
    GROUP BY FirstName 
    ORDER BY [CONTAGEM]

-- QUAL A MEDIA DE PRECO PARA OS PRODUTOS QUE SAO DE PRATA


    SELECT*
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = 'PRODUCTION'
    AND TABLE_NAME = 'PRODUCT'

    SELECT COLOR, AVG (ListPrice) AS [MEDIA]
    FROM Production.Product
    WHERE Color LIKE 'SILVER'
    GROUP BY COLOR
