

--SELECT DISTINCT COUNT(Title)
  --  FROM Person.Person

/*
DESAFIO 1 - QUANTOS PRODUTOS TEMOS CADASTRADOS EM NOSSA TABELA DE PRODUTOS??
*/

SELECT COUNT(*)
    FROM Production.Product

/*
DESAFIO 2 - QUANTOS TAMANHOS DE PRODUTOS TEMOS CADASTRADOS EM NOSSA TABELA??
*/

SELECT *
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = 'PRODUCTION'
    AND TABLE_NAME = 'PRODUCT'

SELECT DISTINCT COUNT ([Size])
   FROM Production.Product