
/* A EQUIPE DE MARKETING PRECISA DE FAZER UMAS PESQUISA SOBRE OS NOMES MAIS COMUNS DE SEUS CLIENTES E PRECISA DO NOME E SOBRENOME DE TODOS OS CLIENTES QUE ESTAO CADASTRADOS NO SISTEMA*/

SELECT FirstName, 
       LastName
  FROM PERSON.Person;